In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
corpus = ["This pasta is very tasty and affordable.","This pasta is not tasty and affordable.","This pasta is delicious and cheap.","Pasta is tasty and pasta tastes good."]
          

#Perform text preprocessing such as stop word removal,stemming,removing punctuations etc.

In [3]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
#from nltk.stem import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer

stop = set(stopwords.words('english'))  #set of stopwords
sno = nltk.stem.SnowballStemmer('english') #initialising the snowball stemmer

def cleanhtml(sentence):  #function to clean the words of any html-tags
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr,' ',sentence)
    return cleantext
def cleanpunc(sentence):  #function to clean the sentence for any punctuaution or special characters
    cleaned = re.sub(r'[?|!|\'|"|#]',r'',sentence)
    cleaned = re.sub(r'[.|,|)|(|\|/]',r' ',cleaned)
    return cleaned
#print(stop)
#print('****************************')
#print(sno.stem('tasty'))

In [4]:
#code for text-preprocessing

i=0
str1=' '
final_corpus=[]
for sent in corpus:
    filtered_sentence=[]
    #print(sent);
    sent=cleanhtml(sent) # remove HTMl tags
    for w in sent.split():
        for cleaned_words in cleanpunc(w).split():
            if((cleaned_words.isalpha()) & (len(cleaned_words)>2)):    
                if(cleaned_words.lower() not in stop):
                    s=(sno.stem(cleaned_words.lower()))
                    filtered_sentence.append(s)
                else:
                    continue
            else:
                continue 
    #print(filtered_sentence)
    str1 = " ".join(filtered_sentence) #final string of cleaned words
    #print(str1)
    #print("***********************************************************************")
    
    final_corpus.append(str1)
print("Corpus before text preprocessing:")
print(corpus)
print("\n")
print('Corpus after text preprocessing:')
print(final_corpus)

Corpus before text preprocessing:
['This pasta is very tasty and affordable.', 'This pasta is not tasty and affordable.', 'This pasta is delicious and cheap.', 'Pasta is tasty and pasta tastes good.']


Corpus after text preprocessing:
['pasta tasti afford', 'pasta tasti afford', 'pasta delici cheap', 'pasta tasti pasta tast good']


In [5]:
vectorizer = CountVectorizer()
bow_vec = vectorizer.fit_transform(final_corpus)
print("Sparse vector representation:\n",bow_vec)

Sparse vector representation:
   (0, 0)	1
  (0, 6)	1
  (0, 4)	1
  (1, 0)	1
  (1, 6)	1
  (1, 4)	1
  (2, 1)	1
  (2, 2)	1
  (2, 4)	1
  (3, 3)	1
  (3, 5)	1
  (3, 6)	1
  (3, 4)	2


#In sparse vector representaion, only the non zero values are shown. Lets convert it to numpy array.

In [6]:
dense_bow = bow_vec.todense()  #converting sparse vector to a dense numpy array
print("Dimensions of dense bow:", dense_bow.shape)
print(dense_bow)

Dimensions of dense bow: (4, 7)
[[1 0 0 0 1 0 1]
 [1 0 0 0 1 0 1]
 [0 1 1 0 1 0 0]
 [0 0 0 1 2 1 1]]


In [7]:
print( vectorizer.vocabulary_ ) #this is the mapping of term to feature indices


{'pasta': 4, 'tasti': 6, 'afford': 0, 'delici': 2, 'cheap': 1, 'tast': 5, 'good': 3}


# Bi-Grams

In [33]:
vectorizer = CountVectorizer(ngram_range=(1,2))
final_bigrams = vectorizer.fit_transform(final_corpus)
print("Dimensions of bi-gram bow:",final_bigrams.shape)

print('Bi-gram bow \n',final_bigrams.todense())

Dimensions of bi-gram bow: (4, 14)
Bi-gram bow 
 [[1 0 0 0 0 1 0 0 1 0 0 1 1 0]
 [1 0 0 0 0 1 0 0 1 0 0 1 1 0]
 [0 1 1 1 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 2 0 1 1 1 1 1 0 1]]


In [8]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
tf_idf_vect = TfidfVectorizer()
final_tf_idf = tf_idf_vect.fit_transform(final_corpus)

In [16]:
features = tf_idf_vect.get_feature_names()
print(features)
print('Shape:',final_tf_idf.shape)

['afford', 'cheap', 'delici', 'good', 'pasta', 'tast', 'tasti']
Shape: (4, 7)


In [13]:
tf_idf = final_tf_idf.todense()
print(tf_idf)

[[ 0.69113141  0.          0.          0.          0.4574528   0.
   0.55953044]
 [ 0.69113141  0.          0.          0.          0.4574528   0.
   0.55953044]
 [ 0.          0.66338461  0.66338461  0.          0.34618161  0.          0.        ]
 [ 0.          0.          0.          0.53477584  0.55813643  0.53477584
   0.34134049]]
